guidance/llms/_openai.py
> [Requesting organization](https://platform.openai.com/docs/api-reference/requesting-organization)
For users who belong to multiple organizations, you can pass a header to specify which organization is used for an API request. Usage from these API requests will count against the specified organization's subscription quota.
<https://platform.openai.com/docs/api-reference/requesting-organization>
=> Add openai.organization

guidance/__init__.py, guidance/_program.py
Fix minor grammatical errors and inconsistencies
=> Clean up documentation

README.md
=> fix role tag's link in README.md

docs/api.rst, guidance/llms/transformers/__init__.py, guidance/llms/transformers/_koala.py, guidance/llms/transformers/_stablelm.py
Based on https://github.com/young-geng/EasyLM/blob/main/docs/koala.md#koala-chatbot-prompts
=> Add support for Koala

notebooks/api_examples/library/role.ipynb
=> Fix one typo

README.md
Fix [148](https://github.com/microsoft/guidance/issues/148)
=> Fix geneach demo code

guidance/_grammar.py, tests/library/test_select.py
=> Allow variables to start with "or" or "else"

guidance/models/__init__.py, guidance/models/_llama_cpp.py, tests/models/test_llama_cpp.py, tests/utils.py
This PR adds a llama.cpp interface to the pythonic2 branch of guidance.
=> add llama.cpp interface

.gitignore, notebooks/anachronism.ipynb, notebooks/guaranteeing_valid_syntax.ipynb
Starting to update the notebooks for the new `guidance` syntax.
Adjusted so far:
- Anachronism detector
- JSON Character generator
=> DOC Update notebooks

guidance/models/__init__.py, guidance/models/_azure_openai.py, guidance/models/_openai.py, notebooks/tutorial.ipynb, notebooks/tutorial_azureai_openai.ipynb, tests/models/test_azureai_openai.py
Make the tutorial marginally less terse, and start work to incorporate Azure OpenAI endpoints
- Add an AzureOpenAI class for use with Azure OpenAI endpoints
- Tweak tutorial notebook
Contains significant contributions from @dfredriksenkbr
=> Update tutorial for Azure OpenAI

guidance/models/_openai.py
This solve the issue https://github.com/guidance-ai/guidance/issues/518
The setting from environment variables is removed because OpenAI will automatically set them through environment variables if None are provided.
see: 
https://github.com/openai/openai-python/blob/e36956673d9049713c91bca6ce7aebe58638f483/src/openai/_client.py#L90-L105
=> Set base_url default as None and remove redundant setting

guidance/models/__init__.py, guidance/models/_anthropic.py, tests/models/test_anthropic.py
Anthropic SDK enables completions inside assistant responses. LiteLLM does not support this functionality
=> Native Anthropic Claude support

notebooks/tutorials/intro_to_guidance.ipynb
Fixed typos in intro_to_guidance.ipynb
=> Fix typos in intro_to_guidance.ipynb

setup.py
Working through `install_requires` in `setup.py` to remove packages which appear to be unimported
=> Dependency trimming

.github/workflows/unit_tests.yml
Add Python 3.12 to the test matrix
=> Add Python 3.12

guidance/__init__.py
This implements the solution to the issue/feature request proposed in https://github.com/guidance-ai/guidance/issues/633
=> Pop first argument from guidance wrapper

.github/workflows/ci_tests.yml
Update the YAML for the CI build:
- Remove PR trigger (was not supposed to be checked in)
- Add a daily build
=> CI Build Schedule

tests/models/test_transformers.py
Only one of the parameterised tests was iterating properly over the targeted models.
=> Fix test_transformers.py

.github/workflows/unit_tests.yml
Start running tests on Windows and MacOS
=> [Test] Expand to other OSes

guidance/_grammar.py, tests/test_grammar.py
This implements the proposed solution in issue https://github.com/guidance-ai/guidance/issues/678
If anyone can suggest other test cases, that would be really appreciated!
=> Support mutual recursion in `GrammarFunctions`

guidance/library/_json.py, tests/library/test_json.py, tests/test_server.py, tests/utils.py
Expand JSON generation capabilities, in particular adding support for:
- `AdditionalProperties`
- `enum`
Possible TODOs (maybe a separate PR depending on timing):
- array `prefixItems`
=> More JSON schema features

tests/library/test_gen.py
A recent merge had not picked up on changes to test infrastructure.
=> Fix for test_gen

guidance/models/transformers/_transformers.py, guidance/models/vertexai/_vertexai.py
Fix issues with fast transformers and partial unicode byte tokens. Now we correctly map tokens to bytes even when those tokens are invalid unicode strings.
=> Fix #681 and #682

.github/workflows/unit_tests_gpu.yml, tests/conftest.py, tests/library/test_gen.py
Enabling some Llama tests to run on the GPU.
=> [Test] Start Llama tests on GPU

.github/workflows/unit_tests_gpu.yml
Initially an attempt to work around this:
https://github.com/scikit-build/cmake-python-distributions/issues/472
In the end, just makes some improvements to the workflow file, since the release of `cmake-python` causing the issue has been yanked.
=> [Test] Fix GPU build

.gitignore, notebooks/tutorials/guidance_acceleration.ipynb, setup.py, tests/test_notebooks.py
Begin working on testing notebooks. This just gets two working, since others are being.... problematic. The tests also don't do anything beyond make sure that the notebook runs without throwing exceptions.
=> [Test] Start on notebook testing

tests/conftest.py, tests/models/test_llama_cpp.py
Enable the tests in `test_llama_cpp.py` using the new fixtures.
=> Enable LlamaCpp Tests

notebooks/art_of_prompt_design/use_clear_syntax.ipynb, notebooks/tutorials/chat.ipynb
Tweak the notebooks to run in the CI build:
- Remove syntax needing Python >=3.10
- Add configurable delays between GPT-4 calls
Unfortunately, there are still occasional issues, but these seem to be fixed by re-running.
=> [Test] Fix notebooks

docs/api.rst, guidance/_grammar.py, guidance/library/_role.py, guidance/models/_azure_openai.py
Various edits to the documentation:
- Add a description for `select()`
- Hook the new `json()` function into the documentation
- Put some basic description of the 'chat' roles into the docs
- Hook `AzureOpenAI` into the docs
=> [Docs] Expand documentation

notebooks/art_of_prompt_design/use_clear_syntax.ipynb, tests/test_notebooks.py
Forgot to propagate all the notebook fixes for `AzureOpenAI` to the final notebook.
=> [Bug] Extra notebook update

guidance/library/_json.py, guidance/models/_mock.py, tests/library/test_json.py
Use `with_temperature()` to support users setting a temperature when generating JSON. Augment `test_json.py` to ensure that the mocked model got called with the specified temperature.
=> [Feature] Add `temperature` to JSON generator

.github/workflows/action_plain_unit_tests.yml, .github/workflows/workflow-pr-gate.yml
Some combinations of LLM and OS don't work very well, likely due to running out of memory. This is starting to make the PR workflow quite ugly, unfortunately.
=> [Build] Fix runs

.github/workflows/workflow-pr-gate.yml
We are trialing larger nodes with more RAM (and disk space)
=> [Build] Use larger build machines

.github/workflows/workflow-pr-gate.yml, tests/conftest.py
Add Phi3 when loaded via GGUF to the test matrix. Do a little renaming of the other Phi3 name for `selected_model` at the same time.
=> [Test] Add Phi3 via GGUF

guidance/models/_azureai_studio.py, guidance/models/_grammarless.py, guidance/models/_openai.py, tests/models/common_chat_testing.py, tests/models/test_azureai_openai.py
Start working on incorporating the token counting metrics to `Grammarless` (i.e. remote, non-guidance-aware) models.
=> [Feature] Metrics for Grammarless models

docs/api.rst, setup.py
Attempt to fix ReadTheDocs:
- Fix references in `api.rst`
- Add dependencies for the `doc` extras package.
=> [Docs] Fix for RTD

guidance/_grammar.py, guidance/library/_gen.py, guidance/library/_json.py, guidance/library/_role.py
Trying to improve the docs:
- Get code blocks working correctly for the `guidance.json()` functionality
- Add some code blocks to `gen()` and `select()`
- Add code blocks to the roles
=> [Doc] Various fixes

guidance/library/_set_attribute.py, tests/library/test_set_attribute.py
set_attribute was not working correctly due to the way closer text was precomputed. This fixes that.
=> Fix set_attribute

guidance/library/__init__.py, guidance/library/_capture.py, tests/library/test_capture.py
This fixes #814 by just making capture work for raw functions.
=> Allow capture of raw functions

guidance/models/_grammarless.py, guidance/models/_model.py, notebooks/tutorials/chat.ipynb, tests/test_notebooks.py
Trying to figure out what is going wrong with the notebook tests. The most common problem appears to be a grammar match problem, so:
- Add more logging to `GrammarlessEngine.get_logits()`
- Try to turn on log output when the notebook runs in the tests
=> [Notebooks] Debugging Attempts

.github/workflows/ci_tests.yml, .github/workflows/notebook_tests.yml
We are getting warnings about a new version of the Azure Login action being available. Update to using it.
=> [Build] Update Azure Login Action

setup.py
Another new version of `transformers`, continued issues with GPT2 on MacOS-ARM
=> [Build] Another troublesome transformer

CONTRIBUTING.md
An addition to yesterday's doc updated about `selected_model` .... need to change the file which holds the list of available models here as well.
=> [Doc] Update Contributing.md

guidance/models/_model.py, tests/unit/test_model.py
Small Bugfix + Test for `set` method on models. Fixes #969
=> [Bug] Fix set behavior with list_append

.github/workflows/action_gpu_basic_tests.yml, .github/workflows/ci_tests.yml, .github/workflows/notebook_tests.yml
It appears that there has been a new CUDA toolkit released, so update the `PATH` appropriately.
=> [Build] Fix CUDA SDK version

guidance/models/transformers/_transformers.py
=> bos_token null check

tests/unit/test_ll.py
see https://github.com/microsoft/llguidance/issues/11
=> add test for "nullable bug"

guidance/models/_model.py, guidance/visual/__init__.py, guidance/visual/_environment.py
Model class now detects if executing within a terminal (as opposed to a notebook). Echo will be forced to false for terminal usage, until interactivity overhaul is merged. Environment class has been ported from overhaul PR.
=> [Hotfix] Echo forced to false on terminal detection.

tests/unit/test_ll.py
We had a test that was assuming incorrect token forcing. I made the test pass with both the previous buggy behavior and new correct one (which is not quite shipped yet in llg).
=> fix test for llg 0.6.9

tests/model_specific/llama_cpp_tests/test_chat_templates.py
@paulbkoch should supercede #1142 -- will merge upon test success
=> [CI HOTFIX] fix `test_chat_format_smoke`

guidance/_ast.py, guidance/library/_audio.py, guidance/models/_base/_client.py, guidance/models/_engine/_tokenizer.py, guidance/models/_openai.py
Adds support for audio prompting to the OpenAI API.
Audio files are currently assumed to be wav (later: should infer from data)
=> [OpenAI] Audio Prompting

setup.py
=> Bump `llguidance` to 0.6.31

guidance/models/_openai.py
Previously, logprobs were only disabled when explicitly generating audio -- turns out they need to be disabled even for text generation when using the `audio-preview` models.
=> [HOTFIX] Disable logprobs in OpenAI `audio-preview` models

guidance/library/_image.py, guidance/library/_video.py, setup.py
=> [Keeping House] Remove unused dependencies

guidance/models/_openai.py
Modifies OpenAIInterpreter's deepcopy implementation to avoid copying the client itself (which can't be pickled due to an RLock)
=> [HOTFIX] Prevent OpenAI client from being copied

guidance/library/_json.py, setup.py
This needs an llg bump in requirements.txt, but it's not released yet.
@hudson-ai can you take a look at the code in the meantime?
=> add lenient= and whitespace_pattern= to json(); use new llg APIs

guidance/models/experimental/_vllm.py
Seems to work for individual captures. Almost probably breaks for list-append. Will test later, merging anyway as this is safely tucked away behind experimental import.
TODO: improve the match infrastructure
=> [Experimental] Support captures with vllm by re-parsing llm output

tests/unit/test_ast.py
Creating some very basic tests of the Lark serialisation of the AST.
=> [Test] Lark/AST smoke testing

guidance/_ast.py, tests/unit/test_ast.py
Probing a little more, generating tests to pin down current behaviour.
=> [Test] Further Lark/AST tests

.github/workflows/ci_tests.yml, .github/workflows/pull_request.yml
Add Python 3.13 to the test matrices
=> [Test] Bump Python

guidance/models/_transformers.py
Should fix CI failures in https://github.com/guidance-ai/guidance/actions/runs/15217336006/job/42805750585
(subtlety with added tokens not being counted in `hf_tokenizer.vocab_size`)
=> [Hotfix] Truncate transformers logits to (correct) vocab size, inclusive of added tokens

guidance/models/_llama_cpp.py, setup.py
Simplify llamacpp implementation by using llguidance's new support for native llamacpp tokenizers
=> [Refactor] Use `llguidance`'s native llamacpp tokenizers 

guidance/_ast.py, guidance/_bg/__init__.py, guidance/_grammar.py, guidance/_guidance.pyi, guidance/_parser.py, guidance/chat.py, guidance/library/_role.py, guidance/library/_subgrammar.py, guidance/library/_substring.py, guidance/models/_openai_base.py, guidance/visual/_message.py, guidance/visual/_renderer.py, guidance/visual/_trace.py
A bit of a yak shave, but the vast number of mypy errors are causing me headaches and making it hard to reason about certain things.
Brings mypy errors from 146 in 23 files down to 72 in 11 files. Not looking at tests right now, just the main lib.
=> [Types] Begin to clean up the repo's type annotations

guidance/models/_transformers.py
Fixing what looks like my fat-fingered mistake.
=> [Hotfix] Set eos/bos properly with slow hf-tokenizer path

guidance/models/_azureai.py, guidance/models/_openai.py, guidance/models/_openai_base.py, guidance/models/experimental/_vllm.py
Should hopefully help make the openai classes a bit easier to extend / implement. They can all share the `_run` method now.
As a bonus, mypy is much less sad now :)
=> [OpenAI,Typing] Add wrapper for OpenAI clients in order to make things more Liskov-y

.github/workflows/ci_credentials.yml, tests/need_credentials/test_openai.py
Redo the OpenAI tests, to match the AzureAI OpenAI ones. For now, these are very much smoke tests.
=> [Test] OpenAI Tests

guidance/_ast.py
Seems merge conflict resolution went a little awry..
=> [HotFix]`SpecialToken` needs `is_allowed_in_lark_terminal=False` (not `is_terminal=False`)

.github/workflows/pypi_upload.yml
No more cibuildwheel -  we don't have any native extensions (C++ / Rust).
=> Update pypi build/release steps.

.github/workflows/pypi_upload.yml
Things break, this should work, maybe. Don't ask.
=> Update OS for pypi build/publish.

guidance/models/_engine/_engine.py, guidance/models/_mock.py
=> [Keeping house] Remove dead code from Engine

guidance/_schema.py
Fix handling of `ff_tokens` in the `TokenUsage.__add__` method.
=> [Fix] TokenUsage __add__

tests/model_specific/test_transformers.py, tests/need_credentials/test_azureai_openai.py, tests/need_credentials/test_azureai_studio.py
Do a little tidying up of some tests. Re-enable previously disabled tests and remove some obsolete ones.
=> [Test] Test tidying

guidance/models/_azureai.py, guidance/models/_base/_interpreter.py, guidance/models/_base/_model.py, guidance/models/_engine/_interpreter.py, guidance/models/_mock.py, guidance/models/_openai.py, guidance/models/_openai_base.py, guidance/models/experimental/_litellm.py, guidance/models/experimental/_vllm.py, ruff.toml
Explicitly add  BLE001, F401 and F541 to the list of lints used by `ruff`.
Also fix B904 in a handful of places.
=> [CQ] Ensure some lints included

guidance/models/_openai_base.py
TokenOutput from openai models wasn't being tagged as generated, messing with vis.
=> [OAI] tag generated tokens as generated

guidance/__init__.py
New release, what's more to say?
=> Bump to 0.2.4

README.md
These docs are minimal. Remove this.
=> Update README.md to remove badge.

tests/unit/test_ast.py
As some other development progresses, want a couple more tests to establish current behaviour
=> [Test] More AST testing

tests/need_credentials/test_azureai_openai.py
Pass env oai chat model rather than `None`
=> [Fix credentialed tests] Pass env oai chat model rather than `None`
