guidance-ai/guidance

guidance/_program.py

It'd be good to ensure that streaming results are available even in the context of an ipywidget callback, like https://github.com/jmandel/guidance-guidance/blob/main/Quiz%20with%20Form%20WIP.ipynb
Importing the `get_ipython` function fixes this for me.

Ensure get_ipython is available even in callbacks

---

guidance/llms/_openai.py

Simply adds `gpt-4-32k` and `gpt-4-32k-0314` to the list of OpenAI models and a newline at the end of file. 
Closes https://github.com/microsoft/guidance/issues/77

Add gpt-4-32k and gpt-4-32k-0314 to OpenAI Models

---

guidance/llms/_transformers.py

Originally pointed out in https://github.com/huggingface/transformers/pull/22797#issuecomment-1556318702 by @fullstackwebdev
By design, some models in `transformers` does not output `past_key_value`. 
This is the case for a new architecture called [RWKV](https://huggingface.co/blog/rwkv), recently integrated in Hugging Face's `transformers`: https://github.com/huggingface/transformers/pull/22797 
For that specific architecture, it is an 'attention free' LLM that does not rely on past key value mechanism to return the cache of the model, as the tokens are always processed one by one. 
This PR adds the support of these custom models, by returning `None` if `past_key_values` is not present in the model's output. The generate method should automatically take care of the rest under the hood in …

Support models that doesn't output `past_key_values`

---

guidance/llms/_transformers.py
guidance/llms/transformers/_llama.py
guidance/llms/transformers/_mpt.py

This adds the `torch_dtype` and `load_in_8bit` quantization parameters for `transformers` models that allow loading larger models with lower VRAM requirements. 
The Llama and MPT subclasses load the model directly, so the parameters had to duplicated there. MPT doesn't seem to support `load_in_8bit` yet, so I just included `torch_dtype` for that one

add quantization parameters for transformers models

---

setup.py

Add `msal` as a dependency since it is imported in the constructor for `guidance.llms.AzureOpenAI`.

fix: Add missing msal dependency.

---

guidance/llms/__init__.py

Hi @slundberg and all, first off great work on this project, I'm very excited to see how it develops.
As per #58 it would be very useful to be able to extend guidance to support additional LLM models to make use of all of the features like token healing and regex sampling.
I understand this project is quite new and you probably want to avoid the cost of maintaining N implementations. If it's an acceptable solution, can we export `LLMSession` and `SyncSession` so external projects can add support on their own?

Export LLMSession and SyncSession

---

guidance/llms/_openai.py

Add a timeout parameter to the POST request to avoid waiting/hanging when the endpoint is unresponsive. A default value of 10 is set for the timeout parameter, which will wait for 10 secs before raising an exception for timeout.

add timeout parameter to POST request

---

README.md

It seems for prompt that (1) provides an example format and (2) has multiple `gen`s, all but the last `gen` need to have proper stop in order to avoid LLM generating all following contents directly. 
The  proverb example in README doesn't provide the stop attribute for `chapter` variable. This will cause it to actually return a completion like `- GPT  11:14:1` which doesn't follow the intended format. This PR fixes this and hopefully makes the point about multi-gen more clear.

Fix GPT proverb example with multiple gens

---

guidance/llms/_openai.py

- Removed the original manually maintained list of chat models
- Edit the script to use regex to parse the model name to determine whether it is a chat model
Related to issues #233 and PR #228

Use regex to parse OpenAI models

---

guidance/llms/_openai.py

Due to the way the regex was written, currently there is always an empty message produced at the end of messages list, eg:
`[{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': 'Whats is the meaning of life??'}, {'role': 'assistant', 'content': ''}]`.
This PR fix the regex and thus remove this empty message.

Remove the last empty assistant message for ChatGPT API call

---

guidance/llms/_openai.py

Adds a few more retryable errors. OpenAI's API is a bit flakey so this makes using it a bit smoother.

Makes OpenAI integration more resilient to failures

---

guidance/llms/_openai.py

- MSALOpenAI LLM needed to define api_key property instead of token property
- init function needed to pass through rest_call argument
- init function needed to set rest headers only if its a rest call

bug fix for MSALOpenAI class

---

guidance/models/transformers/_transformers.py

* vocab_size may not be changed when new tokens added
* ex: that's what happening when using microsoft/phi-1_5
[Comment with explanation](https://github.com/guidance-ai/guidance/issues/453#issuecomment-1819284993)

Use len(tkz) instead of tkz.vocab_size to estimate vocabulary size

---

tests/library/test_gen.py
tests/models/test_llama_cpp.py

When running the tests, there were a number of warnings along the lines of:
```python
tests/library/test_gen.py:119
/home/runner/work/guidance/guidance/tests/library/test_gen.py:119: DeprecationWarning: invalid escape sequence '\d'
pattern = '(Scott is bad)?(\d+)?'
```
Convert the strings to r-strings, so that the backslashes go to the regular expression.

Fix test warnings

---

guidance/_utils.py
guidance/models/_local.py
setup.py
tests/test_utils.py

`scipy` is a slightly hefty dependency at 37.2 MB. It's only used for `softmax` and `log_softmax`, which can be implemented in numpy
The implementations are almost copy-pasted from [scipy](https://github.com/scipy/scipy/blob/v1.11.4/scipy/special/_logsumexp.py), so they are equally efficient:
```python
import numpy as np
import scipy.special
from guidance._utils import log_softmax, softmax
size = (10, 32_000)
logits: np.ndarray = -np.random.uniform(low=0, high=60, size=size)
%timeit log_softmax(logits, axis=-1)
%timeit scipy.special.log_softmax(logits, axis=-1)
%timeit softmax(logits, axis=-1)
%timeit scipy.special.softmax(logits, axis=-1)
```

Remove scipy dependency

---

tests/models/test_llama_cpp.py
tests/utils.py

reduce memory requirements (and probably improve speed) for llama.cpp tests by using a single cached model for all tests

reduce memory requirements (and probably improve speed) for llama.cpp tests

---

guidance/__init__.py
setup.py

`nest_asyncio` is not used anymore so we can remove this dependency.

Drop unused `nest_asyncio`

---

guidance/models/transformers/_transformers.py

Using the `device` parameter already provided by the `Transformers` wrapper doesn't work as intended. It first loads the model (by default on CPU) and then pushes the model to the `device` later. This is inefficient and hasn't been working at all on my end.
Example code snippet for the above:
```Python
from guidance import models
gpt = models.Transformers('gpt2', device='cuda') 
```
Removing the `device` parameter altogether fixes this and removes the confusion of having a `device` parameter that isn't actually directly being used by HF Transformers but only by the wrapper itself.
Also, it doesn't affect anything else since there is a `self.device = self.model_obj.device` that gets the device from the model directly. Also, the tests seem to pass.
It is now only necessary to use …

Fix GPU usage by removing `device` from `Transformers` class wrapper to use the device/device_map directly exposed by HF Transformers in kwargs

---

guidance/__init__.py
guidance/_grammar.py
guidance/_parser.py
guidance/models/_model.py
notebooks/tutorials/intro_to_guidance.ipynb

Streaming updates of variables is crucial for my application yet not supported after the v0.1 update. I found the key is about capturing over the syntax tree and have implemented that in a very naive manner. As the result, we can use `CaptureEvents` to receives the latest `Model` reference every time a token is generated. 
Here is how I use it in my application. Basically, I consume the `event_queue` of a model running in a separate thread and turn it into an iterator. 
```python
LMFunc = Callable[[Model], Model]
def get_vars_recursively(lm: Model) -> Dict[str, str]:
vars = lm._variables
if not lm._event_parent:
return vars
return {**get_vars_recursively(lm._event_parent), **vars}
def iter_guidance_vars(
lm: Model, lm_func: LMFunc, timeout_secs=5
) -> Generator[Dict[str, str], None, …
```

Adding streaming support under guidance v0.1

---

README.md

Fix `Basic Tutorial` link:
- Update "notebooks/tutorial.ipynb" to "notebooks/tutorials/intro_to_guidance.ipynb".

Update "Basic Tutorial" link in README.md

---

guidance/models/_azure_openai.py

Based on the [notebook](https://github.com/guidance-ai/guidance/blob/main/notebooks/api_examples/models/AzureOpenAI.ipynb) and the [AzureOpenAI class code](https://github.com/guidance-ai/guidance/blob/f0c215728d1839781fd0b357fae5c82ffdbd6593/guidance/models/_azure_openai.py#L25), authentication with `API Key authentication` is not supported.
The `azure_deployment` field is required to differentiate between the `model` and its Azure deployment, which is crucial when multiple deployments of the same model exist, or when the deployment is not named after the model..
```python
from guidance import models, gen
import tiktoken
azureai_model = models.AzureOpenAI(
model='gpt-3.5-turbo',
azure_endpoint=azure_endpoint,
azure_deployment='my_crazy_deployment_name',
api_key=api_key,
)
```

WIP: fix: AzureOpenAI authentication to support API Key auth

---

.gitignore
guidance/_grammar.py
guidance/_server.py
guidance/library/_char_set.py
guidance/models/__init__.py
guidance/models/_model.py
guidance/models/_remote.py
notebooks/server_anachronism.ipynb
tests/test_server.py

Some minor tweaks to the server code:
- Adjust `.gitignore` to skip binary produced by `setup.py` on Windows
- Use `response.raise_for_status()` in the server code
- Add Pydantic model for the data sent to the server
- Add a test of bad authentication
- Add a notebook to show basic server use

Minor Server Tweaks

---

guidance/models/_azure_openai.py

Fixes a bug in `AzureOpenAI`. 
If an object is instanciated from a subclass of AzureOpenAI, then the tokenizer is always derived from the model name via tiktoken, even if a tokenizer is passed. 
This will typically fail, because Azure OpenAI deployments have individual model names.
This fixes this case.

fix: missing tokenizer choice in AzureOpenAI subclasses

---

guidance/_json_schema_to_grammar.py
tests/test_json_schema_to_grammar.py

The conditional for adding commas to incomplete sets of properties in `_json_schema_to_grammar._process_object` was incorrect, leading to missing commas in the grammar when the number of properties was too high.
Added a test that fails on the current `main` branch.
@riedgar-ms please take a look when you can

Fix behavior of `_json_schema_to_grammar` for schemas with many properties

---

setup.py

Fixes #618 
This change adds `tests` and `tests.*` to the `exclude` parameter of `find_packages`. Previously, installing guidance would also create an unexpected `tests` subdirectory in the user's `site-packages` directory, which can cause issues if the user has their own package also named `tests`.
I validated this change with the following:
```bash
python3 -m venv .venv
source .venv/bin/activate
pip install .[test]
```
and verified that `.venv/lib/python3.10/site-packages` did not contain a `tests` subdirectory. Furthermore, I verified that running `pytest` still works as expected after the change

Exclude tests packages from distribution

---

guidance/models/_model.py
tests/models/test_model.py

Currently when using the streaming feature, multiple successive additions to the ModelStream object will overwrite each other. This change adds the grammars together instead to preserve each addition.
For example, consider the following code:
```python
import guidance
import guidance.models
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
def main():
model_id = "HuggingFaceH4/zephyr-7b-beta"
quantization_config = BitsAndBytesConfig(
load_in_4bit=True,
bnb_4bit_compute_dtype=torch.bfloat16,
bnb_4bit_use_double_quant=True,
)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
model_id, quantization_config=quantization_config
)
prompt = "Who was the first president of the United States? It was " …
```

Support multiple additions to ModelStream

---

tests/models/test_transformers.py
tests/utils.py

Add basic smoke tests to `transformers` which are parameterised with the name of a Hugging Face model. This is to prevent things like #609 reoccurring.

Add extensible tests to transformers

---

guidance/models/llama_cpp/_llama_cpp.py

The newest version of llama_cpp bindings breaks a few lines of code due to changed variable names and function signatures. I've attempted to make a fix that will be backwards compatible for people using the older version of the llama_cpp library while also working with the new one.
This PR will fix issue https://github.com/guidance-ai/guidance/issues/659

Update _llama_cpp.py to use new bindings

---

guidance/models/__init__.py
guidance/models/_grammarless.py
guidance/models/_togetherai.py
guidance/models/transformers/_transformers.py
notebooks/api_examples/models/TogetherAI.ipynb
tests/models/test_togetherai.py

This PR adds a new `TogetherAI` model, implementing:
`TogetherAICompletion`, `TogetherAIChat`, `TogetherAIInstruct`
In support of [together.ai models](https://docs.together.ai/docs/inference-models).
Together has two library implementations: One is the [together](https://docs.together.ai/docs/inference-python) library, but it also supports the [openai](https://docs.together.ai/docs/openai-api-compatibility) library.
This PR uses the `openai` implementation.
Because of this, we can largely re-use the existing `OpenAI` classes, with some adjustments:
- To support the wide range of open source models, we use `transformers` tokenizers instead of `tiktoken`
- `GrammarlessEngine` now accepts `Tokenizer` instances as well instead of forcing the use of `GrammarlessTokenizer`, allowing us to …

Together.ai Support

---

guidance/_grammar.py

Teeny-tiny little PR: make `Null` inherit from `Terminal`.
As far as I can tell, this is only really useful for preventing something rather silly from blowing up:
```python
@guidance
def null_grammar(lm):
return lm
```
Why would you write this? Don't ask.
Currently, calling this will raise an `AttributeError: 'Null' object has no attribute 'values'` when `replace_grammar_node` does its thing.
An alternative fix would be to explicitly add `Null` to this `isinstance` check in `replace_grammar_node`:
```python
def replace_grammar_node(grammar, target, replacement):
...
if isinstance(current, (Terminal, ModelVariable)):
continue
```
But I think that this PR is a bit more elegant (unless anyone can think of a reason that `Null` wouldn't be `Terminal`).
All tests passing on my end :)

Make Nulls Terminal

---

tests/test_server.py

It appears that the MacOS hosts are running into trouble with the server tests. Try increasing the startup delay, to see if that helps. The [MacOS hosts are slightly lower spec](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) than the Windows and Linux ones.

[Test] MacOS Issue with Server tests

---

.github/workflows/server_tests.yml
.github/workflows/unit_tests.yml
pyproject.toml
tests/test_server.py

The tests in `test_server.py` seem to be a touch temperamental, often failing when the forked server process fails to start in time. In an effort to reduce the re-running of tests, add a `server` mark for these tests, and run in a separate runner job. Use a new workflow file so that everything doesn't get killed by the first failure.

Separate out server tests

---

guidance/library/_gen.py
tests/library/test_gen.py

Calling append on `stop` can cause issues if the same list is used in multiple situations in the same parent context. Using a non-destructive method to update the stop list also makes invoking gen over rpyc possible.

Removed side effect on the stop argument from _gen

---

.github/workflows/unit_tests_gpu.yml
tests/conftest.py

Starting to onboard to the new GPU runner. Just have GPT2 and Phi-2 enabled for now.

Workflow for GPU Runner

---

.github/workflows/ci_tests.yml
.github/workflows/unit_tests.yml
.github/workflows/unit_tests_gpu.yml
notebooks/api_examples/models/AzureOpenAI.ipynb
pyproject.toml
tests/conftest.py
tests/models/test_azureai_openai.py
tests/test_notebooks.py

Start running the Azure AI notebook in tests. This is causing a rethink of some of the testing infrastructure, to add a new `needs_credentials` tag for selecting tests which require API keys and the like.
A fixture for rate limiting is also required, since otherwise we overwhelm our endpoints.

[Test] Enable Azure AI notebook

---

.github/workflows/unit_tests.yml
tests/conftest.py
tests/library/test_gen.py
tests/models/test_transformers.py

Since our notebooks feature Mistral, add an example to our test matrix. The Mistral model itself is loaded via llama-cpp. However:
- Due to #713, have to skip loading Mistral via `transformers`
- To avoid running out of disk space on the GitHub runner machines, we have to narrow the testing in `test_transformers.py`

[Test] Add Mistral to test matrix

---

.github/workflows/unit_tests.yml
.github/workflows/unit_tests_gpu.yml

Today's release of llama-cpp-python appears to be segfaulting more than is strictly desirable. Temporarily add an upper bound.

[Build] Upper bound llama-cpp-python

---

guidance/models/_anthropic.py
guidance/models/_azure_openai.py
guidance/models/_cohere.py
guidance/models/_googleai.py
guidance/models/_lite_llm.py
guidance/models/_model.py
guidance/models/_openai.py
guidance/models/llama_cpp/_llama_cpp.py
guidance/models/transformers/_transformers.py
guidance/models/vertexai/_Codey.py
guidance/models/vertexai/_Gemini.py
guidance/models/vertexai/_PaLM2.py
guidance/models/vertexai/_vertexai.py

This should partly address https://github.com/guidance-ai/guidance/issues/690 where it appears the import of llama-cpp is generating an ImportError exception that is not due to the module not being installed.  This more specific exception will only catch the specific case of the Module not being installed and will leave other exceptions to propagate to the user with more descriptive errors.

replace catches of the ImportError exception with the more specific ModuleNotFoundError exception

---

guidance/models/llama_cpp/_llama_cpp.py

llama_batch_free is failing during python shutdown when the interpreter can set objects to None non-deterministically.  I believe Guidance is properly checking for None in the objects that can be accessed from Guidance, but llama-cpp-python is not, and the native library object in llama-cpp-python is being set to None before it can be called.  Since we're only dealing with memory deallocation here, and since the process is being killed anyway, we can solve this on the Guidance side by not calling llama_batch_free during process termination.

fix for issue #660 where the call to llama_batch_free is failing during process shutdown

---

guidance/models/transformers/_transformers.py

There was an issue extracting the token piece bytes from mistral models in transformers (introduced by a fix for phi-2), this address the mistral issue so it works again. So this fixes #713

Fix #713 for mistral models in transformers

---

guidance/_grammar.py

This removes redundant options, eg. in zero_or_more().

remove redundant options from select()

---

guidance/library/_json.py
tests/library/test_json.py

Resolves issue https://github.com/guidance-ai/guidance/issues/731.
I tried to be as comprehensive with tests as I could, but there are a LOT of cases to cover.
Tag @riedgar-ms

Add support for `prefixItems`, `minItems`, and `maxItems` for `JSON` array generation

---

guidance/library/_substring.py
tests/library/test_substring.py

The `substring()` function wasn't being tested in the builds. Make the following changes:
- Add a `name` argument to `substring()` so we can extract the parts we need
- Tweak the existing test, so that it is not skipped
- Add several tests using the `Mock` which should capture the various automaton states in `substring()`

[Test] Expand testing of substring()

---

.github/workflows/qa_tests.yml
guidance/_grammar.py
guidance/_parser.py
guidance/_utils.py
guidance/library/_block.py
guidance/library/_json.py
guidance/library/_regex.py
guidance/models/_azure_openai.py
guidance/models/_model.py
pyproject.toml
setup.py

Issue: https://github.com/guidance-ai/guidance/issues/729 https://github.com/guidance-ai/guidance/issues/257
- **Set up the structure of mypy installs, now to start typing things**
- **fixed guidance/library/_regex.py:13: SyntaxWarning: invalid escape sequence '\['**
- **First stab at minimal mypy implementation**
This is a non-strict implementation of mypy, with cicd integrated.
After this is approved, we can either slowly move towards a strict implementation, or each PR can simply
choose how much they want/need to contribute to the typing system to help themselves understand the codebase.

First stab at minimal mypy implementation

---

guidance/models/transformers/_transformers.py

Looping over `len(tokenizer)` causes issues when we have to fallback to an underlying sentencepiece model, as the `tokenizer.sp_model` doesn't have context for the extended vocabulary.  I think this is part of the puzzle to solve some persistent issues like https://github.com/guidance-ai/guidance/issues/434?
This is probably broken right now, need to fix up

[WIP?] Trying to fix Transformers tokenizer issues when models have extended vocabulary and/or special tokens

---

guidance/models/llama_cpp/_llama_cpp.py

The new documentation for llama_get_logits is:
// Token logits obtained from the last call to llama_decode()
// The logits for which llama_batch.logits[i] != 0 are stored contiguously
// in the order they have appeared in the batch.
// Rows: number of tokens for which llama_batch.logits[i] != 0
// Cols: n_vocab
LLAMA_API float * llama_get_logits(struct llama_context * ctx);
Since we set llama_batch.logits[i] to true only for the last token, llama_get_logits already returns only the desired slice.

Update _llama_cpp.py based on new contract of llama_get_logits

---

guidance/library/_json.py
tests/library/test_json.py

Add some extra support for JSON schema, to work better with the `langchain` examples:
- Allow definitions to be given in a `definitions` key, as well ad `$defs`
- Allow for single-entry `allOf` blocks

[Feature] Improved JSON Schema support

---

guidance/models/transformers/_transformers.py

The Phi-3 Mini models (e.g. https://huggingface.co/microsoft/Phi-3-mini-4k-instruct) have a total tokenizer vocab size of 32011 (base 32000 plus 11 special tokens), but the model outputs logit vectors of size 32064 (for CUDA performance reasons maybe?). 
I _think_ models that use this trick will always have the "padded" model output at the end, which makes this PR a very clean and simple change to guarantee tokenizer <> model output consistency. This fix will NOT work if the padded outputs are either in the beginning or interspersed throughout the token vector, but I haven't seen a model do that yet. If models do start doing that, we'll need to make significantly heavier changes across the guidance codebase, as we currently heavily rely on the len(tokenizer) to be usable for iteration.

Fix models like phi-3 which have a mismatched tokenizer definition and model output tensor size

---

tests/library/test_json.py

We have been getting intermittent failures in the JSON tests. These are occurring in the 'number' and 'integer' tests, and are almost certainly due to the behaviour of the `model.Mock` class.
Once its supplied string has been exhausted, `Mock` generates random characters (or to be more precise, produces randomised logits for the valid tokens). This means that every now and then, a digit can be produced, which will pass the grammar check for a number, but then fail our round-trip check. This is not a problem for any of our other tests, since in those cases, the final character is forced (e.g. `"` to close a string or `]` to end an array), and there is no possible valid character afterwards.
The fix is to append a character to the string supplied to `Mock` which _never_ appears in the one …

[Test] Fix for JSON tests

---

.github/workflows/ci_tests.yml

Our CI tests are a little flaky, so don't use `fail-fast`. The chances are that some will succeed, so it's best to let the others continue.

[Test] Don't fail fast on CI

---

setup.py

Resolves https://github.com/guidance-ai/guidance/issues/801 . I thought we could use lazy imports and `setup_requires` to get `python setup.py build`, but I kept running into challenges with guaranteeing an install of `PyBind11` and `setuptools_rust` ahead of executing the code. 
Pointing users to `pip` based systems is more robust, especially since we already have a `pyproject.toml` file.

Add guard for running build from setup.py, redirecting users to pip

---

guidance/models/_model.py
pyproject.toml
setup.py

Remove the rust bindings for now since they make development and releasing more complicated.

remove rust bindings for now

---

.github/workflows/pypi_upload.yml

Working in the build mines:
- Drop 32-bit support; it seems unlikely that many models will load on such machines
- Update all actions
- Create a single combined artifact
- Re-enable publishing, conditional on a tag

[Deploy] Updating deployment workflow

---

.github/workflows/pypi_upload.yml

Add some basic testing of the wheels built during the release workflow

[Release] Add smoke test of wheels

---

docs/conf.py

Read The Docs appears to be trying to execute the notebooks as part of the build process. This is causing us to exceed the [RTD build resources](https://docs.readthedocs.io/en/stable/builds.html#build-resources). Since we check-in notebooks with executed cells, we don't need to do this.

[Doc] Deal with notebooks

---

.github/workflows/action_gpu_unit_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml

Exclude another version of `llama-cpp-python` which appears to be causing us issues.
Please note that the non-exclusion of a particular `llama-cpp-python` version means that it is *not known to be troublesome*; it is emphatically **not** a statement that it is known to be untroublesome.

[Build] Adjust llama-cpp-python versions

---

tests/models/test_llama_cpp.py

Some of the LlamaCpp tests used an unusual batchsize, in an effort to test corner cases when the promptsize is close to the batchsize. This lead to us loading the model twice, which might be the (indirect) cause of a lot of segfaults.

[Test] Fix for LlamaCpp tests

---

guidance/library/_gen.py

This should solve suprising issues like #816 where the default limit of 1000 tokens is unexpected.

Remove default max token limit

---

guidance/_parser.py
tests/test_grammar.py

This fixes an issue where selecting or generating empty strings does not get recorded as a named capture (as noted in #826).

Support null captures (Fix #826)

---

.github/workflows/notebook_tests.yml

Our notebook tests are less totally reliable. Try increasing the verbosity of `pytest` in an effort to understand what's going on.

[Test] Increase notebook verbosity

---

notebooks/art_of_prompt_design/use_clear_syntax.ipynb

We have had a number notebook test failures due to Llama-7B not loading correctly on the GPU. Tweak notebooks to run on the CPU instead.

[Test] Notebook reliability

---

.github/workflows/action_gpu_unit_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml

We have a new version of the CUDA Toolkit, so need to update the path we use. Without this, `cmake` wound up unable to find the toolkit when installing `llama-cpp-python`.

[Build] Update for new CUDA Toolkit

---

.github/workflows/action_gpu_unit_tests.yml
.github/workflows/action_plain_unit_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml

It appears that the latest version of `llama-cpp-python` has broken our build. This is most likely due to something in the tokeniser, but pending a deeper investigation, exclude the latest release from the build.

[Build] Quick fix for break

---

.github/workflows/action_gpu_unit_tests.yml
.github/workflows/action_plain_unit_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml
guidance/models/_model.py

This is an improvement on #867, which addressed a build issue by excluding the latest release of `llama-cpp-python` when setting up the GitHub runner machines. The assertion was checking for a self-consistency issue, but it need not be fatal (as evidenced by the fact that we turn it off for Phi3 models). However, if the check fails, it would be helpful to know in bug reports from subsequent failures. Hence, switch to `warnings.warn()`.

[Build] Better fix for break

---

.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml
.github/workflows/workflow-pr-gate.yml
pyproject.toml
setup.py

Python 3.8 is approaching EoL, and is starting to lose support from our dependencies. Bump our minimum supported version to Python 3.9. This allows us to include MacOS-ARM in the builds

[Build] Drop Python 3.8

---

.github/workflows/workflow-pr-gate.yml

The latest release of `llama-cpp-python` (0.2.77) is leading to stuck builds on MacOS-ARM

[Build] MacOS ARM trouble

---

guidance/chat.py

There was a typo in Llama3ChatTemplate for user and assistant roles

Bug] Fix Llama3ChatTemplate

---

CONTRIBUTING.md
tests/conftest.py

Make debugging tests with a particular LLM easier by adding a `GUIDANCE_SELECTED_MODEL` environment variable.
We have the `--selected_model` command line argument for `pytest`, which loads a designated LLM in a fixture (if not set, currently `gpt2cpu` is the default). However, when debugging tests within VS Code, setting that command line argument is non-trivial, and our workaround was to patch the `selected_model_name()` fixture (which reads the command line argument). This change makes the default value for the command line argument be the `GUIDANCE_SELECTED_MODEL` environment variable, and if _that_ is not set, falls back to `gpt2cpu`.

[Test] Environment variable for selected model

---

guidance/library/_json.py
tests/library/test_json.py

This is a super quick PR as I work toward supporting some large JSON schemas I'm working with. All it does is support the `const` keyword in JSON schemas, which are a way of hard coding constant elements: https://json-schema.org/understanding-json-schema/reference/const

[Feature] Constant elements in JSON schemas

---

guidance/models/_byte_tokenizer.py
guidance/models/_grammarless.py
guidance/models/_mock.py
guidance/models/_model.py
guidance/models/_remote.py
guidance/models/_tokenizer.py
guidance/models/llama_cpp/_llama_cpp.py
guidance/models/transformers/_transformers.py

Move the `Tokenizer` class to its own file, and try to define the interface better.
Subsequent changes should build on this, making the invocations of the `Tokenizer` objects more uniform throughout the codebase.

[Refactor] Move Tokenizer to own file

---

guidance/models/_grammarless.py
guidance/models/_openai.py

Doing some general tidying up for `Grammarless` and `OpenAI`:
- Start adding some type hints
- Rationalise imports
- Trim code block apparently overlooked from the `Engine`/`Model` split

[Refactor] Tidy up Grammarless and OpenAI

---

guidance/models/_azureai_studio.py
guidance/models/_grammarless.py
guidance/models/_mock.py
guidance/models/_model.py
guidance/models/_openai.py
guidance/models/_tokenizer.py
guidance/models/llama_cpp/_llama_cpp.py
guidance/models/transformers/_transformers.py

The next stage of refactoring `Tokenizer`; start having the product code conform to the tweaked `Tokenizer` class. Included in this:
- Moving `_joint_tokenize()` onto the `Tokenizer` (as `recode()`), since it really belongs there
- Making the `Tokenizer`s on the 'grammarless' side of things conform to the same contract (i.e. deal with bytes not strings)
- Added some MyPy annotations, and fixed a few issues

[Refactor] Tokenizer refactor continued

---

tests/models/test_azureai_studio.py

The Mistral endpoint is consistently failing in the CI. Take it out of the test matrix for now.

[Fix] Remove Mistral from CI

---

.github/workflows/action_plain_basic_tests.yml
tests/model_specific/test_llama_cpp.py

The latest release of llama-cpp-python (0.2.79) is causing issues with one of our tests (on Windows). The test in question is `test_repeat_calls`, and assumes that at T=0 (the default for `gen()`), then we can repeatedly call a LlamaCpp model and get the same result. This isn't happening, although stepping through the test itself with a debugger, I don't see anything untoward (I'm not seeing a pile up of previous prompts for example).
For now, exclude the latest llama-cpp-python version, but we may want to revisit this test if the problem persists.

[Bug] Exclude llama-cpp-python version

---

guidance/chat.py

It appears that the Mistral chat template has [had an update](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/commit/1296dc8fd9b21e6424c9c305c06db9ae60c03ace), so we need to match this

[Bug] Update Mistral chat template

---

guidance/models/transformers/_transformers.py

This is a fix for #909 . It ensures that any argument common to both `AutoModelForCausalLM.from_pretrained()` and `AutoTokenizer.from_pretrained()` will be passed from the former to the latter when a `TransformersModel` is created. The original issue was only about `trust_remote_code` but there are a few other arguments related to accessing Hugging Face which probably ought to be forwarded as well.
If there are LLM specific arguments which need to be shared, then users should instantiate the tokeniser separately, and pass it in.

[Bug] Passing through kwargs to `TransformersTokenizer`

---

tests/need_credentials/test_azureai_studio.py

We have had to delete the Azure AI deployments used by our tests. Disable them for now, pending redeployment of the relevant endpoints.

[Build] Disable Azure AI tests

---

.github/workflows/workflow-pr-gate.yml
setup.py
tests/server/test_server.py

Use a reduced version of FastAPI, and increase the amount of time we allow for the server process to start. If this continues to be a problem, we should implement a liveliness endpoint, and have that polled by the test (with suitable backoff and retry count).

[Build] Re-enable server tests

---

.github/workflows/action_gpu_basic_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml
README.md
tests/model_specific/test_llama_cpp.py
tests/model_specific/test_transformers.py

The builds have broken in a number of interesting ways:
- The required CMake configuration for `llama-cpp-python` has changed slightly, so update the various workflow files (not to mention the ReadMe).
- It also appears that a new version of Phi3 started giving trouble with another test, so fix that as well
- One of the LLamaCpp tests is consistently failing on Windows (and only Windows), so add a conditional skip

[Build] Various fixes

---

.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml
guidance/chat.py
guidance/models/_azure_guidance.py
notebooks/api_examples/models/AzureOpenAI.ipynb
notebooks/art_of_prompt_design/use_clear_syntax.ipynb
notebooks/tutorials/chat.ipynb
setup.py
tests/need_credentials/test_azureai_openai.py
tests/need_credentials/test_chat_templates.py

Get the CI and Notebook builds working again. The main fix involves the authentication to the AzureAI endpoints; we now have an Entra ID to use, rather than an `api_key`. The instructions are [on the Microsoft site](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure).
Also update the chat templates again, for Phi3 and Mistral. The fix for Mistral is not ideal. It appears that it now 'supports' a `system` message by inserting it into the first `user` message. I don't think our approach can really support this.

[Build] Fix CI and Notebook builds

---

guidance/chat.py
tests/need_credentials/test_chat_templates.py

Add a smoke test of the chat templates, ensuring that they produce output which matches the rendering by the corresponding tokeniser.

[Test] Basic checks on chat templates

---

tests/unit/test_protobuf.py

Adds a unit test that does a round-trip serialization then deserialization of a grammar. This way we can cut out the server entirely, hopefully resulting in a more reliable test.

Protobuf round trip unit test

---

guidance/chat.py
tests/need_credentials/test_chat_templates.py

A couple of issues in the CI build were not caught because the PR was from a fork. There are problems with the Llama2 chat templates, which are addressed here. There are some fixes to the templates themselves, but the handling of the `system` role is so different from how the Guidance context managers work that the test is XFAILed.

[Build] Fix CI build (Llama2 Chat Templates)

---

.github/workflows/ci_tests.yml
setup.py
tests/conftest.py
tests/need_credentials/test_tokenizers.py

Expanding our testing to include Google's Gemma2 model. Since this comes from a repo which requires authentication, only minimal tests are run.

[Test] Include Gemma2 into tests

---

setup.py

The latest release of `transformers` is causing trouble with GPT2 tests on MacOS ARM. Exclude these versions in `setup.py`

[Build] Fix PR Gate

---

.github/workflows/action_gpu_basic_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/workflow-pr-gate.yml
tests/ReadMe.md
tests/_llms_for_testing.py
tests/conftest.py
tests/model_integration/library/test_gen.py
tests/model_specific/llama_cpp/test_chat_templates.py
tests/model_specific/llama_cpp/test_llama_cpp.py
tests/model_specific/test_transformers.py
tests/notebooks/test_notebooks.py

The `AVAILABLE_MODELS` dictionary has been getting rather disorganised and unwieldly of late. This change:
- Separates the dictionary into its own file
- Groups similar models together, so it is easy to find all ways a particular LLM is configured
- Makes the naming convention for the dictionary keys consistent as `<loader>_<model>_<host>`

[Test] Reorganise AVAILABLE_MODELS

---

.github/workflows/action_gpu_basic_tests.yml
.github/workflows/action_plain_basic_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml
setup.py

The latest release of llama-cpp-python is causing trouble with Phi3. Exclude it, and [file a bug](https://github.com/abetlen/llama-cpp-python/issues/1638)

[Build] Exclude llama-cpp-python version

---

.github/workflows/action_gpu_basic_tests.yml
.github/workflows/action_plain_basic_tests.yml
.github/workflows/ci_tests.yml
setup.py

Trying to work around #965 by excluding `transformers` versions in `setup.py` wasn't the best approach (the problem only appears for GPT2 on MacOS-ARM). Move the exclusions into the workflow files, as we do for `llama-cpp-python`

[Build] Move transformers exclusion to workflow

---

guidance/models/transformers/_transformers.py

- Break logic for getting `byte_tokens` from the original huggingface tokenizer out of `__init__` and into separate method
- Break that method down into various different methods, one per approach (using `byte_decoder`, `sp_model`, etc.)
- Don't fall back to fast tokenizer if `byte_decoder` doesn't have all bytes. Instead, just make having all bytes part of the conditional the decides whether to use the `byte_decoder` to get `byte_tokens`
- Remove `hasattr(tokenizer, "get_vocab")` check, as this is always true (@riedgar-ms is this only in new `transformers` versions?)
- Wrap `_byte_tokens_from_vocab` (@ambisinister's code, my name) in a try-except. Since the tokenizer always has a `get_vocab` method, hitting the except is the only path to the gpt-2 fallback byte decoder (@Harsha-Nori it's …

Refector `TransformersTokenizer` and change fallback behavior for `byte_tokens`

---

.github/workflows/action_plain_basic_tests.yml
.github/workflows/workflow-pr-gate.yml

Attempting to deal with #965 . This is not a fix; it just disables GPT2 for the MacOS-ARM tests, which is decidedly less than ideal. Unfortunately, we don't seem able to reproduce this on our own ARM-based Macs.

[Build] Gate fix (MacOS-ARM/GPT2)

---

.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml
guidance/models/_azure_openai.py
tests/need_credentials/test_azureai_openai.py

Get the CI build working again. The core problem appears to be that updates to the `openai` package mean that it does not accept a 1-element string list for the `version` argument anymore. Instead, this must be a string.
We have also moved to having the endpoint information in regular variables, rather than secrets.

[Build] CI Fix

---

.github/workflows/ci_tests.yml
tests/model_integration/test_model.py
tests/utils.py

Now that Guidance-enabled endpoints are available in AzureAI, put them into the test matrix

[Test] Enable Azure Guidance endpoints in test matrix

---

.github/workflows/action_plain_basic_tests.yml
.github/workflows/ci_tests.yml

Move the Azure Guidance endpoint test to its own portion of the CI build. This spawns off another variant of the test workflow YAML (since it need variable and secret access). On the flip side, it does at least run all of the `model_integration` tests.

[Test] Move Azure Guidance in CI

---

guidance/_guidance.py
tests/unit/test_decorator.py

[Bug] del `f._self_call_placeholder_` even when calling `f` raises exception

---

guidance/_grammar.py
guidance/library/_subgrammar.py
guidance/library/_substring.py

Working to improve the type annotations in `_grammar.py`:
- Try to sort out class constructors in `GrammarFunction`.... at least make them less bad
- Introduce a `ComposableGrammar` type (which would ideally be crammed back to `GrammarFunction`)
- Various other minor fixes
- Remove commented out functions
- Re-`black`en

[mypy] Improve types in _grammar.py

---

guidance/_grammar.py
guidance/library/_json.py
guidance/library/_subgrammar.py
setup.py
tests/unit/library/test_json.py

- Pass `json_string` down into Lexeme/llguidance
- Rewrite json_string definition in `library/_json.py`
- Add some tests to ensure that user specified patterns like `.*` can only produce valid json strings

Use `json_string` kwarg from `llguidance 0.1.7`to properly escape json string patterns

---

guidance/__init__.py
guidance/_grammar.py
guidance/_guidance.py

Essentially reopening #638 with some major simplifications allowed by the rust re-write (the serialized grammar now directly supports "references").
Reopening because:
#995 still takes far too long to process the large JSON schema. Line-profiling revealed that ~80% of the time spent constructing the `GrammarFunction` is due to `replace_grammar_node`. In particular, this function has to traverse the entire grammar tree, and we potentially have to call it many times if there is a lot of mutual recursion.
Simply adding a node type that acts as a container (which we can fill after we decide what its contents should be) side-steps this problem entirely.

Remove `Placeholder` and `replace_grammar_node` in favor of pointer-like container object

---

guidance/library/_json.py
tests/unit/library/test_json.py
tests/unit/library/test_sequences.py
tests/utils.py

We currently treat all properties as required, whether or not they are actually in the `required` list.
Implementing a grammar that allows an arbitrary list of grammars to be comma-joined where any subset of the grammars are allowed to be omitted based on a provided sequence of booleans wasn't very trivial... leading and trailing commas were hard to avoid without a recursive definition that's O(2^N) in the worst case (where all properties are optional). This is obviously a bad naive behavior.
Caching brings the O(2^N) to something that I think is closer to O(N) (need to verify).
Need to add some extensive tests too.

[Feature] Support `required` properties in JSON schemas

---

guidance/library/_json.py

In the interest of making it really easy to tell exactly which JSON schema features we do/don't support, I'm making usage of enums a bit more consistent.

[Housekeeping] Clean up Enums to make JSON features more transparent

---

tests/unit/test_ll.py

I have fixed the `LLInterpreter.post_process()` method to be the same as `LLInterpreter.advance_parser()` - they now actually correctly compute the new forced tokens after sampled token (before they would just return the sampled token and only next call to `LLInterpreter.mid_process()` would return the forced tokens).
The change above broke "my" test_ll.py - this fixed it (the test works now with both new and old llguidance). It didn't seem to break anything else (@hudson-ai told me that the new behavior was what he expected anyways).
One day I have to move this test to `llguidance` repo, but it's hard since I don't have any ergonomic way of producing the llguidance grammars there.
cc @Harsha-Nori

fix test_ll for new llguidance with working advance_parser()

---

guidance/_grammar.py
tests/unit/test_grammar.py

Force-feed `ByteParser` an EOS token if it's not done by the time all input has been consumed. This lets us raise an exception when a string fails to complete a grammar

[Bug] Ensure `grammar.match` raises appropriately on incomplete input

---

guidance/library/_json.py
tests/unit/library/test_json.py

We were previously supporting `True`/`False` schemas only when nested in certain places like `items` and `additionalProperties`. This expands our coverage to handle top-level boolean schemas as well.
Note that we will now raise a `ValueError` for `False` schemas, simply because there is nothing we can generate in this case. Alternatively, we return a null grammar... But this may have unforseen consequences.
Added some minimal tests, as we already have decent coverage for the nested cases in the `TestEmptySchema` class. 
Note: developed alongside #1014, which made it much easier to tell whether I had full coverage of every type we accept :)

Support boolean JSON schemas

---

guidance/library/_json.py

What it says on the tin. Does `regex = regex.lstrip("^").rstrip("$")` for any user-passed regex under the json `pattern` keyword.
This strip is necessary in order to use `json` generation with the [big FHIR schema](https://build.fhir.org/fhir.schema.json) because of the odd double anchors they use. It "should" be safe to do this, but I'd like some feedback if there is any dissent.
Note that this could potentially be pulled further down into the `lexeme` code, but I'm not 100% confident that this is "safe" from the perspective of maintaining users' intended semantics.

Strip anchors from JSON regexes

---

guidance/library/_json.py

Add a set containing every single keyword reserved by JSON schema Draft 2020-12.
"Invalid" keywords (rather, unsupported/not-yet-supported keys) are now defined as "any keyword we don't explicitly provide an implementation for that is ALSO a reserved keyword.
This should prevent us from having to manually whitelist non-keywords. Note that I think that the sets/enums of "supported" keys probably needs a second refactor... Not part of this PR though.
For posterity, here's the code I wrote to get the set of all reserved keywords:
```python
from referencing import Registry
from referencing.retrieval import to_cached_resource
import httpx
@to_cached_resource()
def retrieve_with_httpx(url: str) -> str:
response = httpx.get(url)
response.raise_for_status()
return response.text
registry = …
```

JSON reserved keywords

---

guidance/library/_json.py
tests/unit/library/test_json.py

Rather than raising an exception when `required` properties don't have a schema in `properties`, validate against `additionalProperties` (consistent with Draft202012)
Somewhat arbitrarily set key order of resulting objects to:
1. `properties` in order
2. `required` properties mising from `properties` in order
3. any other `additionalProperties`

"required" JSON keys are validated against "additionalProperties" if they are missing from "properties"

---

guidance/_guidance.py

Puts `_self_call_placeholder_` in `threading.local()` to prevent other threads from tricking the decorator into thinking we're in a recursive call. 
Small note: the thread-local storage is in the wrapped function's closure, not an attribute on the function itself.
Tests would be nice, but annoyingly I can only stochastically reproduce the issue as it is due to a race condition. Increasing the number of threads and/or jobs might make the bug occur with higher probability though -- happy to add @mmoskal's repro if we're all okay with a slightly stochastic test...
Closes https://github.com/guidance-ai/guidance/issues/1031

[Bug] Make `_self_call_placeholder_` thread-safe 

---

tests/need_credentials/test_azure_guidance.py

This removes the assumption that tokenizer has only 0-9, and also allows for 0-999 (as in llama 3)
I also limit the length of `test_azure_guidance_suffix` as it doesn't seem to ever get to '\n' with llama3 8b

Make the tests pass with larger tokenizers

---

guidance/__init__.py
guidance/_guidance.py
guidance/_utils.py
tests/unit/test_decorator.py

This PR extends the `@guidance` decorator to work with methods.
I believe this will be invaluable when defining grammars that are implemented as several guidance functions that call each other, particularly if they need to share common parameters. I think that [rewriting `json` as a class](https://github.com/hudson-ai/guidance/blob/json_class_seps/guidance/library/_json.py) will be a good test case for this, and I expect to be able to simplify the implementation with this new machinery as well as enable some otherwise-tricky shared parameters like `separators=(", ", ": ")`.
To achieve this:
- I introduce a `GuidanceFunction` type that is returned when the decorator is called on a function.
- `GuidanceFunction` uses `__get__` descriptor magic to ensure that the function is bound to an …

[Feature] Allow `@guidance` to decorate methods

---

guidance/_grammar.py
guidance/library/_json.py
guidance/library/_subgrammar.py
guidance/library/_substring.py
tests/unit/library/test_json.py
tests/unit/test_ll.py

Fixes issue #1039 by ensuring that the keys for JSON properties validated against `additionalProperties` aren't allowed to match any of the keys for the properties themselves.
I'm still a bit unsure about the API of `And` and `Not`, as well as what the right type hierarchy is (e.g. should they be subclasses of `RegularGrammar`?), but I am comfortable with punting on those questions a bit as they are very much not part of the "public" API yet.

[Bug] [Feature] Fix issue #1039 by exposing `And`, `Not` regex operators from `llguidance`

---

guidance/library/_json.py
setup.py
tests/unit/library/test_json.py

1. Refs are now resolved in full generality, allowing anchors, relative refs, and absolute refs. 
2. Rather than pre-computing the grammars for schemas that happen to live in `$defs`, we now lazily compute grammars upon first reference.
3. Existing ref tests are replaced with the full set of tests from the JSON Schema test suite. Some are xfailed if they depend on other features that we do not (yet) support.
4. Keys in objects are now properly escaped in order to guarantee json.loads-ability (discovered this issue when running the new tests)
NOTE: this introduces a new dependency: `referencing`, which handles ref lookup for us (a fairly non-trivial task).

[Feature] Expand JSON `$ref` resolution

---

guidance/library/_json.py
tests/unit/library/test_json.py

WIP BECAUSE THIS DEPENDS ON STILL-OPEN PR #1061 
When an [applicator](https://json-schema.org/draft/2020-12/json-schema-core#name-applicators) has sibling keywords, JSON schema mandates that both sets of keywords are respected, e.g.
```json
{
"$defs": {"foo": {"type": "integer"}},
"$ref": "#/$defs/foo",
"minimum": 5
}
```
In this schema, "minimum" is a "sibling" to the "$ref", and we need to enforce BOTH the schema in the definition AND the "minimum" keyword.
There are some trivial examples of this general problem, and we can provide implementations for them (in this PR, I also include an implementation for combinations of the "type", "const", and "enum" keywords, which addresses the enum part of #1038). But when no implementation is provided, we need to raise an exception to prevent …

[JSON] Raise exceptions when "sibling" keywords are unhandled

---

guidance/models/_model.py

Just empties the dict of open role blocks when `model.reset` is called. Should close #1071

[BUG] Reset role blocks when `model.reset` is called

---

guidance/_parser.py
guidance/models/_mock.py
guidance/models/_model.py
setup.py
tests/model_integration/test_model.py

Refactors `Engine.__call__` and `TokenParser._parse` coroutine/generator to yield a _future_ wrapping `LLInterpreter.mid_process` (running in a `ThreadPoolExecutor`) such that `mid_process` can run concurrently with the forward pass. This function comes directly from the rust extension, so it releases the GIL and threading *should* be sufficient to ensure true concurrency.
@lochuynh1412 I stole a bit of your code from the interactivity overhaul in order to simplify `Engine.__call__`. I'm definitely introducing a merge conflict for that PR -- happy to help resolve it :)

[Optimization] Advance parser concurrently with model forward pass

---

guidance/_parser.py
guidance/models/_grammarless.py
guidance/models/_model.py
guidance/models/llama_cpp/_llama_cpp.py
guidance/models/transformers/_transformers.py
tests/model_specific/test_transformers.py

Exposing flags for Transformers and LlamaCpp to enable easier experimentation.

Expose fastforward and backtrack llguidance flags 

---

guidance/visual/_environment.py

Missing import error catch in environment detection. This is critical for docker and VM execution of guidance.

[Bug] Fix for environment detection in barebones environments.

---

guidance/models/transformers/_transformers.py

Problem: Logits cannot be converted directly to CPU numpy if its type is in BFloat16
```
File "/home/jc1da/repos/ML/guidance_loc/guidance/models/transformers/_transformers.py", line 513, in get_logits
model_out.logits[0, -1, : len(self.tokenizer.tokens)].cpu().numpy()
TypeError: Got unsupported ScalarType BFloat16
```
Example Code:
```python
model = "Qwen/Qwen2-0.5B-Instruct"
lm = guidance.models.Transformers(
model,
device_map="auto",
trust_remote_code=True,
chat_template=QWen2_ChatTemplate,
torch_dtype=torch.bfloat16,
)
lm += """1 + 1 = add(1, 1) = 2
3 + 5 = add(3, 5) = 8
11 + 9 = add"""
```
@hudson-ai

Force Transformers engine to return float logits

---

setup.py
tests/unit/library/json/test_json.py

- Allow intersection of `pattern`, `format`, and `minLength`/`maxLength` on strings
- Support for pre-Draft2019-09 `additionalItems`
- Reduce cases where we give a warning for `oneOf` (we can infer cases where coercion is guaranteed to be safe)
- Correction to JSON `pattern`'s regex anchoring semantics (patterns not assumed to be anchored by default)
- Minor changes to JSON string generation with `minLength`/`maxLength`: UTF-16 surrogate pairs are no longer allowed

Upgrade llguidance to `0.5.1rc0`

---

.github/workflows/action_gpu_basic_tests.yml
.github/workflows/action_plain_basic_tests.yml
.github/workflows/ci_tests.yml
.github/workflows/notebook_tests.yml

Latest llama-cpp-python 0.3.6 breaks some of our testcases.
Relevant issue: https://github.com/ggerganov/llama.cpp/issues/11197
(Different results returned using same prompt with temperature 0)
Temporarily exclude this version until it's fixed

Exclude llama-cpp-python 0.3.6 in testcases

---

.github/workflows/pypi_upload.yml
.github/workflows/workflow-pr-gate.yml

No need to use the macos-14 runner as it's not actually testing x86 anymore. Switching to just the macos-latest runner (silicon).

Drop macos-14 runner as it's no longer x86

---

guidance/models/_engine/_tokenizer.py
guidance/models/_mock.py
guidance/models/llama_cpp/_llama_cpp.py
guidance/models/transformers/_engine.py
setup.py

@mmoskal if we merge https://github.com/guidance-ai/llguidance/pull/131, this PR will ensure special tokens are properly merked in guidance tokenizers. Doing so ensures that no special tokens are generated inside of grammars like `gen()` and will only be generated when explicitly allowed.
Funny side note -- zero (additional) special handling is required to ensure that generating an end-of-message token causes a chat model to stop. We already have a condition (in guidance -- not llguidance) that takes care of this. Attempting to generate any token outside of the mask is allowed iff an EOS token is allowed and would terminate the grammar. Generating such a token is then interpreted as an EOS token. This condition may have to be revisited, but it's actually working really nicely for now..!

Mark special tokens in tokenizers

---

guidance/models/_openai.py

@Harsha-Nori merging because it's just a tiny hotfix, but I wanted to share the pain...
```
def foo():
yield 42
```
```
def ok():
yield from foo()
list(ok())
```
> [42]
ok
```
def yep():
return foo()
list(yep())
```
> [42]
yep
```
def oh_no():
if False:
yield from foo()
return foo()
list(oh_no())
```
> []
oh no

Fix subtle bug in OpenAI -- returning from a generator

---

guidance/_guidance.py
guidance/library/_block.py
tests/unit/test_decorator.py

@Harsha-Nori we currently do not respect role context managers inside of stateless guidance functions. Even worse, they fail silently! This PR introduces an exception that is raised if we detect that a role is being used in a stateless function.
In the future, we could actually stateless roles working properly, but for now, we should at least raise an exception to let the user know that they are doing something wrong.
Example traceback:
```
Cell In[2], line 3, in foo(lm)
1 @guidance(stateless=True)
2 def foo(lm):
----> 3     with assistant():
4         lm += gen()
5     return lm
File /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py:117, in _GeneratorContextManager.__enter__(self)
115 del self.args, self.kwds, self.func
116 …
```

Raise exception when roles are used in stateless functions

---

guidance/models/transformers/_engine.py

`get_max_length` is deprecated in favor of `get_max_cache_shape` as of transformers v4.48.
Not entirely sure why we're not hitting errors in CI (I updated locally and get exceptions without this fix), but maybe it's just a matter of us running transformers models that are still using legacy tuple-valued `past_key_values`

Update deprecated `transformers.Cache` method

---

tests/unit/library/json/test_allOf.py

Modifies a test to respect property order definition in https://github.com/guidance-ai/llguidance/pull/134
Previously, the "properties" keyword was given precedence over definitions in "allOf", but now we actually care about order. To give it precedence, it had to be moved earlier in the schema.

[JSON] Modify test to stabilize property order

---

guidance/models/llama_cpp/_llama_cpp.py

Some *non-special* tokens return empty bytes when calling `tokenizer.llama.detokenize`. In all cases where this returned empty bytes, we called `llama_cpp.llama_vocab_get_text` and marked the token as special.
While this does return non-empty bytes, they are improperly encoded. E.g., for some models, this function returns `Ġ` (which is two bytes) in place of spaces (which are one byte). In some cases, tokens with 128 bytes were then incorrectly encoded with 256 bytes, overflowing an assertion in `llguidance`.
This PR includes a few fixes:
1. Detect special tokens by calling `tokenizer.llama.token_get_attr` instead of relying on `detokenize` returning empty bytes
2. Re-implement `detokenize`, replacing a hard-coded 32-byte buffer with a parameterized 128-byte buffer, fixing the issues with …

[BUG] Fix llamacpp token overflows

---

guidance/_parser.py
guidance/models/_llama_cpp.py

Mostly just affects experimental vLLM model that runs a tokenizer-naive parser client-side

[HOTFIX]: don't naively decode bytes with `ByteParser`

---

guidance/_ast.py
guidance/models/experimental/_vllm.py

Should fix #1188 -- @marcotcr would you mind testing on your end?

[HOTFIX] Disable max_tokens when re-parsing llm output to avoid missing captures

---

guidance/_parser.py
tests/unit/test_parser.py

Replaces the previous recursive implementation of `consume_bytes` with an iterative approach, preventing deep recursion for long fast-forwards. This improves performance and safety

[HOTFIX] Refactor `ByteParser.consume_bytes` to use a sequential loop

---

guidance/_parser.py
tests/unit/test_parser.py

This reverts commit 0d7f55c11917242a8319d1ec11b35c16243efeb2. The sequential loop introduced an exception when matching grammars with backtracks. A proper solution will be a bit bigger than a hotfix, so punting on that for now and opening a tracking issue, #1198

[HOTFIX] Revert #1197

---

guidance/_ast.py

Noticed that `JoinNode.simplify()` didn't always simplify things (I think). Make it work like `SelectNode`.

[BugFix] Make Join simplify like Select

---

guidance/models/_llama_cpp.py
tests/unit/test_ll.py

The tokenizer for gemma 3 has several tokens that are prefixed by `\x02`, causing our hard-coded `\x02` sentinel byte to fail. Just trying a few more candidates

[BUGFIX] Dynamically determine llamacpp sentinel token for stripping leading tokenizer whitespace

---

setup.py

Now that we're in a new cycle, try bumping the versions of `transformers` and `llama-cpp-python` we use in testing.

[Test] Bump dependencies

---

guidance/models/_llama_cpp.py

This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

[HOTFIX] Resolve logger warnings

---

.github/workflows/ci_tests.yml
tests/conftest.py
tests/model_integration/library/test_gen.py

Add Phi-4 into the CI test matrices. Due to the ongoing `sentencepiece` difficulties, this is not working in the GPU workflows right now.
At the same time, dig into the `model_integration\library\test_gen.py::test_metrics_smoke` test failures. The token counts weren't quite as expected, and this may be due to the extremely simple prompt being represented by a single token in some models. So it wound up being built up character-by-character by the model, requiring more than a single extra token to 'heal.'

[Test] Add Phi-4

---

guidance/_parser.py
guidance/models/_byte_tokenizer.py
guidance/models/_engine/_tokenizer.py
guidance/models/_llama_cpp.py
guidance/models/_mock.py
guidance/models/_transformers.py
setup.py
tests/tokenizer_common.py

1. Refactors all tokenizers to wrap `llguidance.LLTokenizer` rather than constructing an `LLTokenizer` on the fly when we run the parser
2. Doing so allows each `Tokenizer` class to have control over how it constructs said `LLTokenizer`.
- `TransformersTokenizer` is able to call `llguidance.hf.from_tokenizer` directly if we have a `transformers.PretrainedTokenizerFast`, bypassing the slow and error-prone preprocessing step of inferring `byte_tokens`
- `TransformersTokenizer` falls back to the old approach for non-fast tokenizers
- `LlamaCppTokenizer`, `MockTokenizer`, and `ByteTokenizer` all use the old approach (manually specifying a list of `byte_tokens`). They also implement their own `encode` methods, which are notably passed to the `LLTokenizer` that they wrap
Note that we may get a …

[Refactor] Use `llguidance`'s native wrapper for `transformers.PretrainedTokenizerFast` where possible

---

guidance/models/_openai_base.py

OpenAI disallows the `x-guidance` key (which we use for setting whitespace, k/v separators, and leniency options), rather than ignoring it as an unknown key. We need to omit it from the schemas we pass to OpenAI to avoid errors.
TODO: warn the user this is happening if they chose any non-standard options?

[Hotfix] Pop `x-guidance` key when passing schemas to OpenAI

---

guidance/models/_transformers.py

@riedgar-ms should fix the error in this CI test? Seems they may have changed the API of these cache classes though, so the fix may not be backwards compatible...
https://github.com/guidance-ai/guidance/actions/runs/15221677677/job/42818226368

[Hotfix] Transformers `{Hybrid,Static}Cache` attrs / init args

---

guidance/models/_engine/_tokenizer.py
setup.py
tests/model_integration/test_tokenizers.py
tests/model_specific/llama_cpp_tests/test_llama_cpp.py
tests/tokenizer_common.py

Fixes regression introduced by #1218, where the llamacpp tokenizer fails to parse special tokens. Fixed by adding behavior and corresponding kwarg to llguidance, exposed here (with default True).
Added explicit test for this, as our existing tests did not cover this behavior!

[Bugfix] Ensure special tokens are tokenized as such (broken by #1218)

---

tests/model_specific/llama_cpp_tests/test_llama_cpp.py

Correct a typo in one of the skips for `test_llamacpp.py::test_repeat_calls` which should get the Linux CI build to Green.
Note #1225 though.

[Test] Correct skip for `test_repeat_calls`

---

guidance/_utils.py
tests/model_specific/llama_cpp_tests/test_llama_cpp.py

`tests/model_specific/llama_cpp_tests/test_llama_cpp.py::test_repeat_calls`
- Remove `UserWarning` on xfail condition and use `pytest.xfail` instead
`tests/model_specific/test_visual.py`: 48 warnings
- Accessing the 'model_fields' attribute on the instance is deprecated. Instead, you should access this attribute from the model class. Deprecated in Pydantic V2.11 to be removed in V3.0

[Hygiene] Fix some warnings in the tests

---

guidance/library/_json.py

A quirk in the serialization code... we have no tests of this edge case, as it is only hit when there's no capture name / temperature / etc.
Introduced regression in #1245
@riedgar-ms fyi

[Hotfix] JsonNode must be wrapped in RuleNode

---

guidance/models/_openai_base.py

Result of a typo. @riedgar-ms seems we're not even smoke testing oai json -- I think we need a single list of tests like these, parameterized across oai, litellm with various backends, azure inference, aoai, ... Will add this week if I get a chance

[Hotfix] Invalid type for 'response_format': expected an object, but got an array instead.

---

guidance/_ast.py
guidance/models/_transformers.py
tests/conftest.py
tests/model_specific/llama_cpp_tests/test_chat_templates.py
tests/model_specific/test_transformers.py

While I'd like to get rid of our machinery around chat templates entirely (see https://github.com/guidance-ai/guidance/pull/1249), I think that is a little ways off. In the meantime, this PR improves our tests of said machinery and fixes a few bugs that these improved tests caught.
- Modifies llama_cpp `test_chat_format_smoke` to make it use the *actual* `Model` rather than a `Mock`, ensuring that we're actually testing the code path that would be hit under typical usage
- Relaxes the assertions made in `test_chat_format_smoke` from `assert jinja2_render.contains(str(lm))` to `assert is_subarray(tokenize(str(lm)), tokenize(jinja2_render))`, as tokenization is not one-to-one
- Adds an equivalent test for transformers in `test_chat_format_smoke`
- `TransformerTokenizer` was not correcly …

Improve chat-format smoke tests; fix bug in TransformereTokenizer where chat template was not being inferred

---

guidance/chat.py

Should fix CI failures: https://github.com/guidance-ai/guidance/actions/runs/15684027851
New tests discovered that Phi4 chat template was missing.

[CI Fix] Add Phi4 chat template to the cache

---

guidance/models/_engine/_engine.py

Previously, the logits were skewed substantially when masking was applied since the values inside the mask variable were either 0 or 200 depending on whether they were allowed or not allowed.  The value of 200 was multiplied by the logits, which skewed them much higher than intended, leading to the top token most likely always being selected instead of probabilistically selecting them.  A further fix to temperature is included.  Previously temperatures of 0.0 were treated the same as temperature = 1.0 since softmax was used on the original logits instead of deterministically selecting the highest logit token.

fix bug that was skewing token probabilities when masking was applied

---

.git-blame-ignore-revs

Add commit 95b1bbe75b049c9d3bdc0346d09116b76f736472 generated by https://github.com/guidance-ai/guidance/pull/1280 to `.git-blame-ignore-revs`

Ignore ruff-the-codebase rev

---

guidance/models/_azureai.py
guidance/models/_openai_base.py
guidance/models/experimental/_litellm.py

Just simplifies things a little bit:
Makes `OpenAIClientWrapper.streaming_chat_completions` take a more generic `list[dict[str, Any]]` rather than `list[Message]`, letting us call `TypeAdapter(list[Message]).dump_python(messages)` in just one place (`BaseOpenAIInterpreter`) rather than in each `streaming_chat_completions` implementation

[Refactor] Move TypeAdapter serialization from `OpenAIClientWrapper` to `BaseOpenAIInterpreter`

---

setup.py

Use the newly stabilized llguidance dependency; no changes needed on our side.

Bump `llguidance` dependency to `1.0.1`

---

.github/workflows/ci_credentials.yml
.github/workflows/ci_docs.yml
.github/workflows/notebook_tests.yml

Trigger three of the CI builds (Credentials, Doc, Notebooks) on pushes to `main`. These are builds which would be in the gate but for the fact that they access secrets, and breakages need to be caught quickly.

[Build] Trigger CI on push to `main`

---

guidance/models/_azureai.py
guidance/models/_openai_base.py
guidance/models/experimental/_litellm.py

Largely a duplicate of #1314; attempting independent fix. Generally changes `log_probs` to `logprobs`, to match the underlying API.

[OAI/AOAI] Fix error passing `top_logprobs` when `logprobs` is False

---

guidance/models/_engine/_engine.py

Copy logits array before calling `apply_temp_and_sampling_params`, as this function mutates said logits.

Fix duplicated apply_temp_and_sampling_params on logits array

---

tests/notebooks/test_notebooks.py

The 'Clear Syntax' notebook has been updated for use in the new website, and is now working. Tidy up some of the test infrastructure code which is no longer needed (and caused trouble on Windows).
Closes #1004 .

[Notebooks] Re-enable 'Clear Syntax' notebook

---

guidance/_ast.py
tests/model_integration/test_model.py

We had a bug in the processing of capture names. If a capture name is also a valid Lark rule name, then it can be left in place. Otherwise (e.g. if it mixes upper and lower case), we have to normalise it, and use the `capture="OriginalName"` feature of our Lark grammar. This wasn't being done.
Fixes #1172

[Bug] Normalised capture names not preserved

---

guidance/models/_openai_base.py

For GPT-5, it appears the `max_tokens` arg changes (or may well have been changed a while ago, but we did not update to the new name, and GPT-5 only supports the latter). There will be further updates for GPT-5, though

[OpenAI] Change kwarg for token limit

---

.github/workflows/call_cpu_tests.yml
.github/workflows/call_gpu_tests.yml
.github/workflows/ci_linux.yml
.github/workflows/notebook_tests.yml

It appears that we may not have been passing the CodeCov token around properly. Remedy this oversight.
Also ensure that `gpustat` is installed when it may be appropriate.

[Build] Pass through token for code coverage

---

guidance/_parser.py
guidance/_schema.py
guidance/models/_base/_model.py
guidance/models/_base/_state.py
guidance/models/_engine/_engine.py

Adds some usage metrics:
1. `mask_times_ms` is a list of latencies that includes both 
- the time to advance the parser (with related overheads such as tokenizing the backtrack bytes, recoding the tokens if needed, ...)
- the time spent calculating the mask
2. `mask_overheads_ms` is the same, *less* the time that was parallelized with the logit computation
- note: only the time spent calculating the mask can be parallelized 
Also adds a (private) method to Model: `_reset_usage`
@JC1DA happy to just return summary stats, but I figured the whole list might be more useful if you're looking for more distributional quantities.

Add mask latency to usage

---

guidance/_parser.py
guidance/models/_engine/_engine.py

@JC1DA not sure how consistently you were able to repro the "negative time" issue, but please test this out and see if it fixes your issue. I don't see any logic errors with the timings, so all "should" be non-negative. Potentially, the issue has to do with timing in a thread, and `time.monotonic` should help if this is indeed the case. Perhaps a little over-zealously, I converted all the other `time.time` calls to `monotonic` too -- shouldn't hurt.

Switch from `time.time` to `time.monotonic` for engine timing

---

guidance/models/_engine/_engine.py

The LLama3 chat template also needs the BOS token, so add that in when rendering the template.

[Bug] Fix `chat_completion()` for Llama3

---

tests/model_specific/common_chat_testing.py
tests/need_credentials/test_azureai_openai.py

Small tweaks to the AOAI tests, to allow use of GPT-5 models:
- Temperature is not supported with reasoning models, so remove this for GPT-5
- The 'reasoning' portion of the response was using up the token budget, so for GPT-5 models, expand `max_tokens`. Ideally we'd use `max_completion_tokens` but that's not currently exposed by `gen()`

[Test] Fix AOAI Tests for GPT-5
